# handle different name strings for common regions
region_restriction = {
    "AH": "H",
    "MH": "H",
    "PH": "H",
    "A": "A",
    "EC": "EC",
    "PHC": "PHC",
    "PIC": "PIC", 
    "PRC": "PRC",
    "APH": "PHC",
    "MPH": "PHC",
    "PPH": "PHC",
}

dataset_labels = [
          'alison', 
          'autumn', 
          'beach',
          'bus', 
          'cafe', 
          'camera-cuts', 
          'car',
          'days-of-summer', 
          'douche', 
          'elevator',
          'family-home', 
          'gallery',
          'ikea', 
          'indoor-setting',
          'karaoke-bar', 
          'mckenzie', 
          'mckenzie-faces', 
          'millie',
          'millie-faces', 
          'office',  
          'other-cafe', 
          'park', 
          'paul',
          'paul-faces', 
          'persons', 
          'punch-bar', 
          'rachel', 
          'rachel-faces',
          'record-store', 
          'restaurant', 
          'rhoda', 
          'scenes', 
          'secretary',
          'soccer-field', 
          'street', 
          'summer', 
          'summer-apartment',
          'summer-body-sequence', 
          'summer-child-bedroom', 
          'summer-faces',
          'summer-presence', 
          'summer-speaking', 
          'the-graduate', 
          'theater',
          'tom', 
          'tom-apartment', 
          'tom-child-bedroom', 
          'tom-faces',
          'tom-speaking', 
          'train', 
          'vance', 
          'vance-faces', 
          'wedding-venue']